version: '3.9'

networks:
  camagru-network:
    name: camagru-network

services:
  app:
    build: .
    command: npm run start  # run dev -> nodemon / run start -> normal
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    depends_on:
      - db
    networks:
      - camagru-network
    volumes:
      - .:/app
      - /app/node_modules # Ensures node_modules is not overwritten

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - camagru-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - camagru-network

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    depends_on:
      - app
    networks:
      - camagru-network

volumes:
  postgres_data:
  pgadmin_data:
  node_modules:
